heat_template_version: 2016-04-08

description: >
  Neutron LBaaS service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  MysqlVirtualIPUri:
    type: string
    default: ''

outputs:
  role_data:
    description: Role data for the Neutron LBaaS role.
    value:
      config_settings:
      step_config: |
        include ::tripleo::profile::base::neutron::lbaas
